directory<-getwd()
directory1<-paste(c(directory,"/UCI HAR Dataset/test/X_test.txt"),collapse='')
directory2<-paste(c(directory,"/UCI HAR Dataset/test/y_test.txt"),collapse='')
directory3<-paste(c(directory,"/UCI HAR Dataset/test/subject_test.txt"),collapse='')
directory4<-paste(c(directory,"/UCI HAR Dataset/train/X_train.txt"),collapse='')
directory5<-paste(c(directory,"/UCI HAR Dataset/train/y_train.txt"),collapse='')
directory6<-paste(c(directory,"/UCI HAR Dataset/train/subject_train.txt"),collapse='')
directory7<-paste(c(directory,"/UCI HAR Dataset/activity_labels.txt"),collapse='')
directory8<-paste(c(directory,"/UCI HAR Dataset/features.txt"),collapse='')
print("*Starting reading files*")
print("*Reading files in test folder*")
test_folder_x<-read.table(directory1,header=FALSE)
test_folder_y<-read.table(directory2,header=FALSE)
test_folder_sub<-read.table(directory3,header=FALSE)
print("*Reading files in train folder*")
train_folder_x<-read.table(directory4,header=FALSE)
train_folder_y<-read.table(directory5,header=FALSE)
train_folder_sub<-read.table(directory6,header=FALSE)
print("*Reading activity_labels.txt and feature.txt files*")
act_lab<-read.table(directory7,header=FALSE)
feature<-read.table(directory8,header=FALSE,colClasses="character")
print("*All files read.Binding all files*")
test_var<-cbind(test_folder_sub,test_folder_y,test_folder_x)
train_var<-cbind(train_folder_sub,train_folder_y,train_folder_x)
bind<-rbind(test_var,train_var)
colnames(bind)[1:2]<-c("subject","actid")
colnames(bind)[3:ncol(bind)]<-feature[,1]
print("*Getting column indexes*")
index<-c(grep("mean\\(\\)",names(bind)),grep("std\\(\\)",names(bind)))
dataset<-bind[,c(1,2,index)]
colnames(act_lab)<-c("actid","activity")
print("*Loading package dplyr*")
library(dplyr)
data<-inner_join(act_lab,dataset,by="actid")
data<-data[,2:ncol(data)]
print("*Here is the output...*")
View(data %>% group_by(activity,subject) %>% summarise_each(funs(mean)))